-- MySQL Script generated by MySQL Workbench
-- Thứ bảy, 12 Tháng 12 Năm 2020 15:53:07 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema iptv
-- -----------------------------------------------------
-- Ứng dụng microservice xây dựng hệ thống quản lý và monitor resource cho phòng headend trung tâm dịch vụ truyền hình
DROP SCHEMA IF EXISTS `iptv` ;

-- -----------------------------------------------------
-- Schema iptv
--
-- Ứng dụng microservice xây dựng hệ thống quản lý và monitor resource cho phòng headend trung tâm dịch vụ truyền hình
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `iptv` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `iptv` ;

-- -----------------------------------------------------
-- Table `iptv`.`env`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`env` ;

CREATE TABLE IF NOT EXISTS `iptv`.`env` (
  `name` VARCHAR(30) NOT NULL COMMENT 'Tên môi trường',
  `desc` VARCHAR(45) NULL COMMENT 'mô tả thêm',
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = 'môi trường làm việc\n';


-- -----------------------------------------------------
-- Table `iptv`.`vlan_provider`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`vlan_provider` ;

CREATE TABLE IF NOT EXISTS `iptv`.`vlan_provider` (
  `name` VARCHAR(30) NOT NULL COMMENT 'tên nhà cung cấp vlan\n',
  `address` VARCHAR(60) NULL COMMENT 'Địa chỉ nhà cung cấp nếu có\n',
  `desc` VARCHAR(60) NULL COMMENT 'mô tả thêm',
  PRIMARY KEY (`name`))
ENGINE = InnoDB
COMMENT = 'Quản lý nhà cung cấp vlan cho hệ thống';


-- -----------------------------------------------------
-- Table `iptv`.`vlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`vlan` ;

CREATE TABLE IF NOT EXISTS `iptv`.`vlan` (
  `id` INT NOT NULL COMMENT 'id vlan',
  `env` VARCHAR(30) NOT NULL COMMENT 'môi trường\n',
  `provider` VARCHAR(45) NOT NULL COMMENT 'nhà cung cấp vlan',
  `desc` VARCHAR(60) NULL COMMENT 'mô tả thêm',
  `status` TINYINT(2) NULL DEFAULT 1,
  `date_create` DATETIME NULL,
  `date_update` DATETIME NULL,
  PRIMARY KEY (`id`, `env`, `provider`),
  INDEX `fk_vlan_vlan_provider_idx` (`provider` ASC),
  CONSTRAINT `fk_vlan_vlan_provider`
    FOREIGN KEY (`provider`)
    REFERENCES `iptv`.`vlan_provider` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Vlan: quản lý vlan trên hạ tầng network';


-- -----------------------------------------------------
-- Table `iptv`.`satellite_dishe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`satellite_dishe` ;

CREATE TABLE IF NOT EXISTS `iptv`.`satellite_dishe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Tên chảo',
  `diameter` DECIMAL(5,2) NULL COMMENT 'Đường kính chảo\n',
  `location` VARCHAR(60) NULL COMMENT 'Nơi lắp đặt',
  `status` TINYINT(2) NULL DEFAULT 1 COMMENT '1 - inuse, 0 - not use, 2 maintenance',
  `env` VARCHAR(30) NULL,
  `date_create` DATETIME NULL,
  `date_update` DATETIME NULL,
  `vlan_id` INT NOT NULL,
  `vlan_provider` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Name_UNIQUE` (`name` ASC),
  INDEX `fk_satellite_dishe_env1_idx` (`env` ASC),
  INDEX `fk_satellite_dishe_vlan1_idx` (`vlan_id` ASC, `vlan_provider` ASC, `env` ASC),
  CONSTRAINT `fk_satellite_dishe_env1`
    FOREIGN KEY (`env`)
    REFERENCES `iptv`.`env` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_satellite_dishe_vlan1`
    FOREIGN KEY (`vlan_id` , `vlan_provider` , `env`)
    REFERENCES `iptv`.`vlan` (`id` , `provider` , `env`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'Quản lý các chảo thu tín hiệu vệ tinh ';


-- -----------------------------------------------------
-- Table `iptv`.`agent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`agent` ;

CREATE TABLE IF NOT EXISTS `iptv`.`agent` (
  `ip_control` CHAR(15) NOT NULL COMMENT 'ip giao tiếp hệ thống, bắt b',
  `ip_multicast` CHAR(15) NULL COMMENT 'Ip nhận tín hiệu multicast, có thể có hoặc không',
  `cpu` SMALLINT(3) NULL COMMENT 'số CPU\n',
  `ram` SMALLINT(3) NULL COMMENT 'Dung lượng RAM GiB\n',
  `disk` SMALLINT(4) NULL COMMENT 'Dung Lượng Disk GiB',
  `location` VARCHAR(60) NULL COMMENT 'Điểm đặt',
  `monitor` TINYINT NULL COMMENT 'bật giám sát\n',
  `alarm` TINYINT NULL COMMENT 'Bật cảnh báo\n',
  `date_create` DATETIME NULL,
  `date_update` DATETIME NULL,
  PRIMARY KEY (`ip_control`),
  UNIQUE INDEX `ip_control_UNIQUE` (`ip_control` ASC))
ENGINE = InnoDB
COMMENT = 'Quản lý các server monitor\n';


-- -----------------------------------------------------
-- Table `iptv`.`encoder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`encoder` ;

CREATE TABLE IF NOT EXISTS `iptv`.`encoder` (
  `name` VARCHAR(45) NOT NULL COMMENT 'tên encode',
  `ip` VARCHAR(45) NULL COMMENT 'ip của encode\n',
  `location` VARCHAR(60) NULL COMMENT 'Nơi đặt encode',
  `hardware` VARCHAR(45) NULL COMMENT 'Phần cứng',
  `env` VARCHAR(30) NULL COMMENT 'môi trường ',
  `desc` VARCHAR(45) NULL COMMENT 'Mô tả thêm',
  `date_create` VARCHAR(45) NULL COMMENT 'ngày tạo',
  `date_update` VARCHAR(45) NULL COMMENT 'Ngày cập nh',
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `ip_UNIQUE` (`ip` ASC),
  INDEX `fk_encoder_env1_idx` (`env` ASC),
  CONSTRAINT `fk_encoder_env1`
    FOREIGN KEY (`env`)
    REFERENCES `iptv`.`env` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Quản lý encoder, thiết bị chuyển tín hiệu gốc thành tín hiệu phục vụ khác hàng';


-- -----------------------------------------------------
-- Table `iptv`.`group_channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`group_channel` ;

CREATE TABLE IF NOT EXISTS `iptv`.`group_channel` (
  `name` VARCHAR(30) NOT NULL COMMENT 'Tên nhóm kênh ',
  `desc` VARCHAR(60) NULL COMMENT 'mô tả ',
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iptv`.`channel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`channel` ;

CREATE TABLE IF NOT EXISTS `iptv`.`channel` (
  `name` VARCHAR(30) NOT NULL COMMENT 'Tên kênh\n',
  `group` VARCHAR(30) NULL COMMENT 'Nhóm kênh: chính thống, địa phương, nước ngoài, vvv',
  `desc` VARCHAR(60) NULL COMMENT 'mô tả thêm',
  `date_create` DATETIME NULL,
  `date_update` DATETIME NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_channel_group_channel1_idx` (`group` ASC),
  CONSTRAINT `fk_channel_group_channel1`
    FOREIGN KEY (`group`)
    REFERENCES `iptv`.`group_channel` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Quản lý kênh truyền hình\n';


-- -----------------------------------------------------
-- Table `iptv`.`profile_quality`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`profile_quality` ;

CREATE TABLE IF NOT EXISTS `iptv`.`profile_quality` (
  `id` SMALLINT(5) NOT NULL,
  `quality` CHAR(45) NOT NULL COMMENT 'Tên tiêu chuẩn chất lượng\n',
  `description` VARCHAR(60) NULL COMMENT 'mô tả thêm\n',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Chất lượng kênh truyền\n';


-- -----------------------------------------------------
-- Table `iptv`.`multicast_ip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`multicast_ip` ;

CREATE TABLE IF NOT EXISTS `iptv`.`multicast_ip` (
  `ip` CHAR(15) NOT NULL COMMENT 'ip v4 ',
  `desc` VARCHAR(60) NULL COMMENT 'Mô tả thêm\n',
  PRIMARY KEY (`ip`))
ENGINE = InnoDB
COMMENT = 'ip';


-- -----------------------------------------------------
-- Table `iptv`.`profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`profile` ;

CREATE TABLE IF NOT EXISTS `iptv`.`profile` (
  `channel` VARCHAR(30) NOT NULL COMMENT 'Tên kênh truyền hình\n',
  `ip` CHAR(15) NULL,
  `quality` SMALLINT(5) NOT NULL COMMENT 'chất lượng kênh',
  `group` VARCHAR(30) NULL COMMENT 'nhóm profile\n',
  `desc` VARCHAR(60) NULL COMMENT 'mô tả thêm',
  `env` VARCHAR(30) NOT NULL COMMENT 'môi trường \n',
  `date_create` DATETIME NULL,
  `date_update` DATETIME NULL,
  `vlan_id` INT NOT NULL,
  `vlan_provider` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`channel`, `quality`, `env`),
  INDEX `fk_profile_profile_quality1_idx` (`quality` ASC),
  INDEX `fk_profile_profile_ip1_idx` (`ip` ASC),
  INDEX `fk_profile_vlan1_idx` (`vlan_id` ASC, `vlan_provider` ASC, `env` ASC),
  CONSTRAINT `fk_profile_channel1`
    FOREIGN KEY (`channel`)
    REFERENCES `iptv`.`channel` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_profile_quality1`
    FOREIGN KEY (`quality`)
    REFERENCES `iptv`.`profile_quality` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_profile_ip1`
    FOREIGN KEY (`ip`)
    REFERENCES `iptv`.`multicast_ip` (`ip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profile_vlan1`
    FOREIGN KEY (`vlan_id` , `vlan_provider` , `env`)
    REFERENCES `iptv`.`vlan` (`id` , `provider` , `env`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Kênh truyền hình phân loại theo chất lượng';


-- -----------------------------------------------------
-- Table `iptv`.`group_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`group_profile` ;

CREATE TABLE IF NOT EXISTS `iptv`.`group_profile` (
  `name` VARCHAR(30) NOT NULL COMMENT 'Tên nhóm profile',
  `desc` VARCHAR(60) NULL COMMENT 'mô tả thêm\n',
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = 'nhóm các profile';


-- -----------------------------------------------------
-- Table `iptv`.`encoder_has_vlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`encoder_has_vlan` ;

CREATE TABLE IF NOT EXISTS `iptv`.`encoder_has_vlan` (
  `encoder_name` VARCHAR(45) NOT NULL,
  `vlan_id` INT NOT NULL,
  `vlan_env` VARCHAR(30) NOT NULL,
  `vlan_provider` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`encoder_name`, `vlan_id`, `vlan_env`, `vlan_provider`),
  INDEX `fk_encoder_has_vlan_vlan1_idx` (`vlan_id` ASC, `vlan_env` ASC, `vlan_provider` ASC),
  INDEX `fk_encoder_has_vlan_encoder1_idx` (`encoder_name` ASC),
  CONSTRAINT `fk_encoder_has_vlan_encoder1`
    FOREIGN KEY (`encoder_name`)
    REFERENCES `iptv`.`encoder` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encoder_has_vlan_vlan1`
    FOREIGN KEY (`vlan_id` , `vlan_env` , `vlan_provider`)
    REFERENCES `iptv`.`vlan` (`id` , `env` , `provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iptv`.`encoder_has_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`encoder_has_profile` ;

CREATE TABLE IF NOT EXISTS `iptv`.`encoder_has_profile` (
  `encoder_name` VARCHAR(45) NOT NULL,
  `profile_channel` VARCHAR(30) NOT NULL,
  `profile_quality` SMALLINT(5) NOT NULL,
  `profile_env` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`encoder_name`, `profile_channel`, `profile_quality`, `profile_env`),
  INDEX `fk_encoder_has_profile_profile1_idx` (`profile_channel` ASC, `profile_quality` ASC, `profile_env` ASC),
  INDEX `fk_encoder_has_profile_encoder1_idx` (`encoder_name` ASC),
  CONSTRAINT `fk_encoder_has_profile_encoder1`
    FOREIGN KEY (`encoder_name`)
    REFERENCES `iptv`.`encoder` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encoder_has_profile_profile1`
    FOREIGN KEY (`profile_channel` , `profile_quality` , `profile_env`)
    REFERENCES `iptv`.`profile` (`channel` , `quality` , `env`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iptv`.`group_profile_has_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`group_profile_has_profile` ;

CREATE TABLE IF NOT EXISTS `iptv`.`group_profile_has_profile` (
  `group_profile_name` VARCHAR(30) NOT NULL,
  `profile_channel` VARCHAR(30) NOT NULL,
  `profile_quality` SMALLINT(5) NOT NULL,
  `profile_env` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`group_profile_name`, `profile_channel`, `profile_quality`, `profile_env`),
  INDEX `fk_group_profile_has_profile_profile1_idx` (`profile_channel` ASC, `profile_quality` ASC, `profile_env` ASC),
  INDEX `fk_group_profile_has_profile_group_profile1_idx` (`group_profile_name` ASC),
  CONSTRAINT `fk_group_profile_has_profile_group_profile1`
    FOREIGN KEY (`group_profile_name`)
    REFERENCES `iptv`.`group_profile` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_profile_has_profile_profile1`
    FOREIGN KEY (`profile_channel` , `profile_quality` , `profile_env`)
    REFERENCES `iptv`.`profile` (`channel` , `quality` , `env`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iptv`.`satellite_dishe_has_multicast_ip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`satellite_dishe_has_multicast_ip` ;

CREATE TABLE IF NOT EXISTS `iptv`.`satellite_dishe_has_multicast_ip` (
  `satellite_dishe_id` INT NOT NULL,
  `multicast_ip_ip` CHAR(15) NOT NULL,
  PRIMARY KEY (`satellite_dishe_id`, `multicast_ip_ip`),
  INDEX `fk_satellite_dishe_has_multicast_ip_multicast_ip1_idx` (`multicast_ip_ip` ASC),
  INDEX `fk_satellite_dishe_has_multicast_ip_satellite_dishe1_idx` (`satellite_dishe_id` ASC),
  CONSTRAINT `fk_satellite_dishe_has_multicast_ip_satellite_dishe1`
    FOREIGN KEY (`satellite_dishe_id`)
    REFERENCES `iptv`.`satellite_dishe` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_satellite_dishe_has_multicast_ip_multicast_ip1`
    FOREIGN KEY (`multicast_ip_ip`)
    REFERENCES `iptv`.`multicast_ip` (`ip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `iptv`.`agent_has_vlan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`agent_has_vlan` ;

CREATE TABLE IF NOT EXISTS `iptv`.`agent_has_vlan` (
  `agent_ip_control` CHAR(15) NOT NULL,
  `vlan_id` INT NOT NULL,
  `vlan_env` VARCHAR(30) NOT NULL,
  `vlan_provider` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`agent_ip_control`, `vlan_id`, `vlan_env`, `vlan_provider`),
  INDEX `fk_agent_has_vlan_vlan1_idx` (`vlan_id` ASC, `vlan_env` ASC, `vlan_provider` ASC),
  INDEX `fk_agent_has_vlan_agent1_idx` (`agent_ip_control` ASC),
  CONSTRAINT `fk_agent_has_vlan_agent1`
    FOREIGN KEY (`agent_ip_control`)
    REFERENCES `iptv`.`agent` (`ip_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agent_has_vlan_vlan1`
    FOREIGN KEY (`vlan_id` , `vlan_env` , `vlan_provider`)
    REFERENCES `iptv`.`vlan` (`id` , `env` , `provider`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iptv`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`user` ;

CREATE TABLE IF NOT EXISTS `iptv`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` CHAR(30) NULL,
  `email` CHAR(60) NULL,
  `phone` CHAR(15) NULL,
  `address` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iptv`.`user_has_multicast_ip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`user_has_multicast_ip` ;

CREATE TABLE IF NOT EXISTS `iptv`.`user_has_multicast_ip` (
  `user_id` INT NOT NULL,
  `multicast_ip` CHAR(15) NOT NULL,
  `pou` VARCHAR(60) NULL COMMENT 'Purpose of use: mục đích sử dụng ',
  `date_create` DATETIME NULL COMMENT 'Ngày tạo\n',
  `date_update` DATETIME NULL COMMENT 'ngày cập nhật',
  PRIMARY KEY (`user_id`, `multicast_ip`),
  INDEX `fk_user_has_multicast_ip_multicast_ip1_idx` (`multicast_ip` ASC),
  INDEX `fk_user_has_multicast_ip_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_user_has_multicast_ip_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `iptv`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_multicast_ip_multicast_ip1`
    FOREIGN KEY (`multicast_ip`)
    REFERENCES `iptv`.`multicast_ip` (`ip`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iptv`.`monitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`monitor` ;

CREATE TABLE IF NOT EXISTS `iptv`.`monitor` (
  `agent_ip_control` CHAR(15) NOT NULL,
  `profile_channel` VARCHAR(30) NOT NULL,
  `profile_quality` SMALLINT(5) NOT NULL,
  `profile_env` VARCHAR(30) NOT NULL,
  `status_signal` TINYINT NULL,
  `status_video` TINYINT NULL,
  `status_audio` TINYINT NULL,
  `is_mnt_signal` TINYINT NULL,
  `is_mnt_video` TINYINT NULL,
  `is_mnt_audio` TINYINT NULL,
  `is_enable` TINYINT NULL,
  `date_update` DATETIME NULL,
  PRIMARY KEY (`agent_ip_control`, `profile_channel`, `profile_quality`, `profile_env`),
  INDEX `fk_agent_has_profile_profile1_idx` (`profile_channel` ASC, `profile_quality` ASC, `profile_env` ASC),
  INDEX `fk_agent_has_profile_agent1_idx` (`agent_ip_control` ASC),
  CONSTRAINT `fk_agent_has_profile_agent1`
    FOREIGN KEY (`agent_ip_control`)
    REFERENCES `iptv`.`agent` (`ip_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agent_has_profile_profile1`
    FOREIGN KEY (`profile_channel` , `profile_quality` , `profile_env`)
    REFERENCES `iptv`.`profile` (`channel` , `quality` , `env`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `iptv`.`agent_has_group_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `iptv`.`agent_has_group_profile` ;

CREATE TABLE IF NOT EXISTS `iptv`.`agent_has_group_profile` (
  `agent_ip_control` CHAR(15) NOT NULL,
  `group_profile_name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`agent_ip_control`, `group_profile_name`),
  INDEX `fk_agent_has_group_profile_group_profile1_idx` (`group_profile_name` ASC),
  INDEX `fk_agent_has_group_profile_agent1_idx` (`agent_ip_control` ASC),
  CONSTRAINT `fk_agent_has_group_profile_agent1`
    FOREIGN KEY (`agent_ip_control`)
    REFERENCES `iptv`.`agent` (`ip_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agent_has_group_profile_group_profile1`
    FOREIGN KEY (`group_profile_name`)
    REFERENCES `iptv`.`group_profile` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `iptv`.`env`
-- -----------------------------------------------------
START TRANSACTION;
USE `iptv`;
INSERT INTO `iptv`.`env` (`name`, `desc`) VALUES ('local', 'Local');
INSERT INTO `iptv`.`env` (`name`, `desc`) VALUES ('real', 'Phục vụ khách hàng');
INSERT INTO `iptv`.`env` (`name`, `desc`) VALUES ('live', 'Live stream');
INSERT INTO `iptv`.`env` (`name`, `desc`) VALUES ('test', 'Chỉ dùng để test');

COMMIT;

