# Generated by Django 2.2.12 on 2020-12-13 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IptvEnviroment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'enviroment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MulticastIp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('desc', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'multicast_ip',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VlanProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('desc', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'vlan_provider',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vlanid', models.CharField(max_length=30)),
                ('desc', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.BooleanField()),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvresource.IptvEnviroment')),
                ('vlan_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvresource.VlanProvider')),
            ],
            options={
                'db_table': 'vlan',
                'managed': True,
                'unique_together': {('vlan_provider', 'env', 'vlanid')},
            },
        ),
        migrations.CreateModel(
            name='UserHasMulticastIp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('multicast_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvresource.MulticastIp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_has_multicast_ip',
                'managed': True,
                'unique_together': {('multicast_ip', 'user')},
            },
        ),
    ]
