# Generated by Django 2.2.12 on 2020-12-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iptvresource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encoder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('ip', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('hardware', models.CharField(blank=True, max_length=45, null=True)),
                ('desc', models.CharField(blank=True, max_length=45, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('enviroment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvresource.IptvEnviroment')),
            ],
            options={
                'db_table': 'encoder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SatelliteDishe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.BooleanField()),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvresource.IptvEnviroment')),
            ],
            options={
                'db_table': 'satellite_dishe',
                'managed': True,
                'unique_together': {('id', 'env')},
            },
        ),
        migrations.CreateModel(
            name='SatelliteDisheHasMulticastIp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('multicast_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvresource.MulticastIp')),
                ('satellite_dishe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.SatelliteDishe')),
            ],
            options={
                'db_table': 'satellite_dishe_has_multicast_ip',
                'managed': True,
                'unique_together': {('multicast_ip', 'satellite_dishe')},
            },
        ),
        migrations.CreateModel(
            name='EncoderHasVlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encoder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Encoder')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvresource.Vlan')),
            ],
            options={
                'db_table': 'encoder_has_vlan',
                'managed': True,
                'unique_together': {('vlan', 'encoder')},
            },
        ),
    ]
