# Generated by Django 2.2.12 on 2020-12-13 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satellitedishe',
            old_name='status',
            new_name='is_enable',
        ),
    ]
