# Generated by Django 2.2.12 on 2020-12-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iptvresource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_control', models.CharField(max_length=15, unique=True)),
                ('ip_receive_multicast', models.CharField(blank=True, max_length=15, null=True)),
                ('cpu', models.SmallIntegerField(blank=True, null=True)),
                ('ram', models.SmallIntegerField(blank=True, null=True)),
                ('disk', models.SmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=60, null=True)),
                ('is_monitor', models.BooleanField()),
                ('is_alarm', models.BooleanField()),
                ('signal_monitor', models.BooleanField()),
                ('video_monitor', models.BooleanField()),
                ('audio_monitor', models.BooleanField()),
                ('run_thread', models.IntegerField(blank=True, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'agent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AgentHasVlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvresource.Vlan')),
            ],
            options={
                'db_table': 'agent_has_vlan',
                'managed': True,
                'unique_together': {('vlan', 'agent')},
            },
        ),
    ]
