# Generated by Django 2.2.12 on 2020-12-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
