# Generated by Django 2.2.12 on 2021-01-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20201222_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='version',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
