# Generated by Django 2.2.12 on 2020-12-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent', '0001_initial'),
        ('device', '0001_initial'),
        ('channel', '0001_initial'),
        ('iptvresource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('desc', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'group_profile',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProfileQuality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quality', models.CharField(max_length=45, unique=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'profile_quality',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('desc', models.CharField(blank=True, max_length=60, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('is_original', models.BooleanField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.Channel')),
                ('encoder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Encoder')),
                ('multicast_ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvresource.MulticastIp')),
                ('profile_quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvprofile.ProfileQuality')),
                ('vlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvresource.Vlan')),
            ],
            options={
                'db_table': 'profile',
                'managed': True,
                'unique_together': {('profile_quality', 'channel', 'multicast_ip')},
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status_signal', models.IntegerField(blank=True, null=True)),
                ('status_video', models.IntegerField(blank=True, null=True)),
                ('status_audio', models.IntegerField(blank=True, null=True)),
                ('signal_monitor', models.IntegerField(blank=True, null=True)),
                ('video_monitor', models.IntegerField(blank=True, null=True)),
                ('audio_monitor', models.IntegerField(blank=True, null=True)),
                ('is_enable', models.BooleanField()),
                ('date_update', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvprofile.Profile')),
            ],
            options={
                'db_table': 'monitor',
                'managed': True,
                'unique_together': {('profile', 'agent')},
            },
        ),
        migrations.CreateModel(
            name='GroupProfileHasProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvprofile.GroupProfile')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvprofile.Profile')),
            ],
            options={
                'db_table': 'group_profile_has_profile',
                'managed': True,
                'unique_together': {('profile', 'group_profile')},
            },
        ),
        migrations.CreateModel(
            name='EncoderInputProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('encoder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Encoder')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvprofile.Profile')),
            ],
            options={
                'db_table': 'encoder_input_profile',
                'managed': True,
                'unique_together': {('encoder', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='AgentHasGroupProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent')),
                ('group_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptvprofile.GroupProfile')),
            ],
            options={
                'db_table': 'agent_has_group_profile',
                'managed': True,
                'unique_together': {('agent', 'group_profile')},
            },
        ),
    ]
