# Generated by Django 2.2.12 on 2020-12-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptvprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='audio_monitor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='signal_monitor',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='status_audio',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='status_signal',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='status_video',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='video_monitor',
            field=models.BooleanField(),
        ),
    ]
