# Generated by Django 2.2.12 on 2020-12-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptvprofile', '0002_auto_20201213_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileState',
            fields=[
                ('state', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'profile_state',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iptvprofile.ProfileState'),
        ),
    ]
