# Generated by Django 2.2.12 on 2020-12-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptvprofile', '0003_auto_20201213_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='iptvprofile.ProfileState'),
        ),
    ]
