# Generated by Django 2.2.12 on 2020-12-13 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('desc', models.CharField(blank=True, max_length=60, null=True)),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('date_update', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'channel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('desc', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'group_channel',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupChannelHasChannel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.Channel')),
                ('group_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channel.GroupChannel')),
            ],
            options={
                'db_table': 'group_channel_has_channel',
                'managed': True,
                'unique_together': {('channel', 'group_channel')},
            },
        ),
    ]
